-- 코드를 입력하세요
SELECT A.AUTHOR_ID
     , B.AUTHOR_NAME
     , A.CATEGORY
     , SUM(A.PRICE * C.COUNT_SALES) TOTAL_SALES
  FROM BOOK       A
     , AUTHOR     B
     , ( SELECT BOOK_ID
              , SUM(SALES) COUNT_SALES
           FROM BOOK_SALES
          WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-01'
          GROUP BY BOOK_ID
       ) C
 WHERE A.BOOK_ID   = C.BOOK_ID
   AND A.AUTHOR_ID = B.AUTHOR_ID
 GROUP BY A.AUTHOR_ID, A.CATEGORY
 ORDER BY A.AUTHOR_ID ASC, A.CATEGORY DESC