-- 코드를 작성해주세요
# SELECT DATE_FORMAT(YM, '%Y') AS YEAR
# , ROUND(AVG(PM_VAL1), 2) AS 'PM10'
# , ROUND(AVG(PM_VAL2), 2) AS 'PM2.5'
# FROM AIR_POLLUTION
# -- WHERE LOCATION1 = "경기도" AND LOCATION2 = "수원"
# WHERE LOCATION2 = '수원'

# GROUP BY YEAR
# ORDER BY YEAR

SELECT YEAR(YM) AS YEAR
, ROUND(AVG(PM_VAL1), 2) AS 'PM10'
, ROUND(AVG(PM_VAL2), 2) AS 'PM2.5'
FROM AIR_POLLUTION
WHERE LOCATION2 = '수원'
GROUP BY YEAR
ORDER BY YEAR

/*
DATE_FORMAT은 STRING으로 나오고, YEAR는 DATE 타입으로 나온다.. 그래서.. 그래서.. 며칠동안.. 틀렸었다....
*/
