SELECT '1Q' AS QUARTER
     , COUNT(ID) AS ECOLI_COUNT
  FROM ECOLI_DATA
 WHERE QUARTER(DIFFERENTIATION_DATE) = 1
 UNION
 SELECT '2Q' AS QUARTER
     , COUNT(ID) AS ECOLI_COUNT
  FROM ECOLI_DATA
 WHERE QUARTER(DIFFERENTIATION_DATE) = 2
 UNION
 SELECT '3Q' AS QUARTER
     , COUNT(ID) AS ECOLI_COUNT
  FROM ECOLI_DATA
 WHERE QUARTER(DIFFERENTIATION_DATE) = 3
 UNION
 SELECT '4Q' AS QUARTER
     , COUNT(ID) AS ECOLI_COUNT
  FROM ECOLI_DATA
 WHERE QUARTER(DIFFERENTIATION_DATE) = 4