-- 코드를 입력하세요
SELECT B.PRODUCT_ID
     , A.PRODUCT_NAME
     , SUM(B.AMOUNT * A.PRICE) TOTAL_SALES
  FROM FOOD_PRODUCT A
     , FOOD_ORDER   B
  WHERE A.PRODUCT_ID = B.PRODUCT_ID
    AND DATE_FORMAT(B.PRODUCE_DATE, '%Y-%m') = '2022-05'
  GROUP BY B.PRODUCT_ID
  ORDER BY 3 DESC, 1