-- 코드를 입력하세요
SELECT B.MEMBER_NAME
     , C.REVIEW_TEXT
     , DATE_FORMAT(C.REVIEW_DATE, '%Y-%m-%d') REVIEW_DATE
  FROM ( SELECT MEMBER_ID
              , RANK() OVER (ORDER BY COUNT(*) DESC) SEQ
           FROM REST_REVIEW
          GROUP BY MEMBER_ID
       ) A
     , MEMBER_PROFILE B
     , REST_REVIEW    C
 WHERE SEQ = 1 
   AND A.MEMBER_ID = C.MEMBER_ID
   AND C.MEMBER_ID = B.MEMBER_ID
 ORDER BY C.REVIEW_DATE, C.REVIEW_TEXT