SELECT T2.ITEM_ID
     , T3.ITEM_NAME
     , T3.RARITY
  FROM ITEM_INFO T1
     , ITEM_TREE T2
     , ITEM_INFO T3
 WHERE T1.RARITY = 'RARE'
   AND T1.ITEM_ID = T2.PARENT_ITEM_ID
   AND T2.ITEM_ID = T3.ITEM_ID
 ORDER BY T2.ITEM_ID DESC