SELECT TA.ID       AS ID
     , TA.GENOTYPE AS GENOTYPE
     , TB.GENOTYPE AS PARENT_GENOTYPE
  FROM ECOLI_DATA TA
     , ECOLI_DATA TB
 WHERE TA.PARENT_ID = TB.ID
   AND TA.GENOTYPE & TB.GENOTYPE = TB.GENOTYPE
 ORDER BY ID