SELECT B.YEAR YEAR
     , B.MAX_SIZE_OF_COLONY - A.SIZE_OF_COLONY YEAR_DEV
     , ID
  FROM ECOLI_DATA A
     , (SELECT MAX(SIZE_OF_COLONY) MAX_SIZE_OF_COLONY
             , YEAR(DIFFERENTIATION_DATE) YEAR
          FROM ECOLI_DATA
         GROUP BY YEAR(DIFFERENTIATION_DATE)
       ) B
 WHERE YEAR(A.DIFFERENTIATION_DATE) = B.YEAR
 ORDER BY YEAR, YEAR_DEV
 
